[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5"
rocket_ws = "0.1"

serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }

common = { path = "../common" }